### ISSUE TITLE
Workflows and stakeholders interaction

### ISSUE THREAD

**Issue by jefmoura** [blooparksystems/Helpdesk#1]
- [x] Generic workflow
- [x] Order workflow
- [x] Send the workflows to Wiki
- [x] Table with criteria
  ![generic_workflow](https://cloud.githubusercontent.com/assets/4620451/12633427/d31e903c-c558-11e5-87a5-e2a4c1fb1832.png)

**Comment by tainaml** [comment]
The employee will open an order -> It goes to the Manager for feedback ; If approved It goes back to the employee portal; Then it goes to the HelpDesk.
Once it's on HelpDesk it goes first to the Agent who's gonna see/read the issue and pass it to the Manager for a feedback (if need), as well as the admin .  Agent ->Manager ->Admin

How about the interaction between Agent - Manager   Manager-Admin ?  :)
Do you agree with me?

Cheers

**Comment by jholze** [comment]
@jefmoura would be nice to see you in the hipchat channel. thx

**Comment by jholze** [comment]
@jefmoura @tainaml i think we should better define the stake holder roles. Maybe a table with criteria about each role. 

btw. a very good helpdesk is the one from http://kb.mailchimp.com/ and check the branch for helpdesk under http://runbot.odoo.com/runbot/repo/git-github-com-odoo-dev-enterprise-8?search= 

(i) with click on the blue button, you can open the feature instance to check it

**Comment by jholze** [comment]
@jefmoura about your diagramm, i think both portal systems should be part of the odoo system als well. Looks like they are separate tools at the moment.

**Comment by jholze** [comment]
@jefmoura i created a first wiki page https://github.com/blooparksystems/Helpdesk/wiki its part of this project. Better to place all planning stuff there instead of a ticket. hope it will help 

bye

**Comment by jefmoura** [comment]
@jholze Thank you for your advice. I'll move the documentation to wiki and I was thinking more about the system and I understand better now, so I'll create another diagram.
We'll create a table with criteria about each stack holder role to be clearer. Thanks!

**Comment by jefmoura** [comment]
@jholze We'll create a table with criteria about each stack holder role to be clearer. Thanks!

**Comment by jefmoura** [comment]
#### Order workflow

![order_workflow](https://cloud.githubusercontent.com/assets/4620451/12631609/5ee08f82-c539-11e5-834b-78fb8d01d208.png)

**Comment by jefmoura** [comment]
- We changed the first diagram and built the order workflow.
- We created a table with criteria about each role as mentioned early. It's in the [Stakeholders Table](https://github.com/blooparksystems/Helpdesk/wiki/Stakeholders-Table) wiki page.
- We created pages to document the system.
