### ISSUE TITLE
Fix: Syntax error [High priority]

### ISSUE THREAD

**Issue by jefmoura** [blooparksystems/Helpdesk#25]
There are some errors on project. We have to fix the code and create unit tests.
- [x] Change rules from _security/ir.model.access.csv_
- [x] Fix syntax - _views/order_view.xml_
- [x] Fix syntax - _models/models.py_
- [x] Move _models.py_ to main folder
- [x] Move _security/security.xml_ to top of data in ___openerp__.py_

**Comment by jefmoura** [comment]
There is an error now that I can't understand and I don't find explanation on internet.
The error is below:

_AssertionError: Element openerp has extra content: data, line 3_

**Comment by jefmoura** [comment]
- I tested the _order_view.xml_ in different XML Validators on internet and every one showed me: **No erros found**
- I posted a question in Odoo Forum, maybe we will have a quick answer.

This is the link to the page:
https://www.odoo.com/fr_FR/forum/help-1/question/assertionerror-element-openerp-has-extra-content-data-line-3-96949

**Comment by jholze** [comment]
@jefmoura i ask in the team if someone can help and tweet the question.

**Comment by ghost** [comment]
Hi
The element sheet is not closed.

```
                <sheet>
                    <group>
                        <field name="name"/>
                        <field name="description"/>
                        <field name="message"/>
                    </group>
                <sheet>
```

**Comment by christophlsa** [comment]
@fshahy I think this was already fixed in this branch (see the linked commit).

@jefmoura I think the problem here is that for some views the definitions are outside of `<field name="arch" type="xml">`.

So look for example in https://github.com/blooparksystems/Helpdesk/blob/fix-syntaxError-25/views/order_view.xml#L14:
- I don't think that this button is allowed on this position (either in the "arch"-part or into the header).
- I'm not sure if `<field name="help" type="html">` is allowed in `ir.ui.view` (found this only in `ir.actions.act_window`).

**Comment by jefmoura** [comment]
Thanks @jholze 
Yes, I fixed it in a branch @fshahy , thanks!

@christophlsa I see that there are many issues in my code. I'm understanding better how to implement a module to the odoo system every day. I have some answers in odoo forum, so I think that with your help and the forum people I can improve my code now. Thanks for your time!

**Comment by jefmoura** [comment]
Problems, explanation:

1. because all views had the same name.
2. groups missing module name, so I create new groups in *base*.
3. move buttons to right place, tree view.
4. recursive *act_window_id* in *act_window.view*, replace to act_window with only *view_id*

**Comment by jefmoura** [comment]
Problems, explanation:
1. all views had the same name, so I changed them.
2. groups missing module name, so I create new groups in _base_.
3. buttons were outside of `<field name="arch" type="xml"><tree>`, so I moved buttons to right place.
4. recursive _act_window_id_ in _act_window.view_, replace to act_window with only _view_id_
