### ISSUE TITLE
Modeling objects [High priority]

### ISSUE THREAD

**Issue by jefmoura** [blooparksystems/Helpdesk#5]
We must define the structure of the helpdesk objects.
To initialize we should define:
- [x] order
- [x] answer
- [x] track/follow

**P.S.: Define the relationship between objects, inclusive.**

**Comment by jefmoura** [comment]
- Employee and Manager we will use the *res.partner*
- Agent, Manager and Admin are *res.user*
- *res.partner* and *res.user* are models that the Odoo system provides already to map customer and system user.

**Comment by tainaml** [comment]
Good!

**Comment by jefmoura** [comment]
- I created two different diagrams to understand better the relationship between the objects.
- In the first diagram we can see the attributes that each have.

#### Class Mapping

![mapping_db](https://cloud.githubusercontent.com/assets/4620451/12698376/21dc7196-c782-11e5-80a7-33ad502ff051.png)

#### Relationship Mapping

![workflow_acts](https://cloud.githubusercontent.com/assets/4620451/12698346/a874259c-c781-11e5-9892-760f8acc5bbd.png)

**Comment by jefmoura** [comment]
I created a page on the [Wiki](https://github.com/blooparksystems/Helpdesk/wiki/Object-Mapping), where these diagrams are shown.
All documentation is there.
