### ISSUE TITLE
Create Models [High priority]

### ISSUE THREAD

**Issue by jefmoura** [blooparksystems/Helpdesk#6]
Defined the object structures, we have to create the models to map the relational objetcs.
To start we can create models to these objects:
- [x] Order
- [x] Answer
- [x] Track/Follow

**P.S.: Don't forget to include the relationship of fields.**

**Comment by jefmoura** [comment]
- Employee and Manager we will use the _res.partner_
- Agent, Manager and Admin are _res.user_
- _res.partner_ and _res.user_ are models that the Odoo system provides already to map customer and system user.

**Comment by jefmoura** [comment]
I found the need to create some methods of the models that I believe to be part of this task.
- Classes:
  - _Order_
  - _Answer_
- Methods to each one:
  - _write()_
  -  _create()_

**Comment by tainaml** [comment]
class TicketAdmin(admin.ModelAdmin)
    list_display = ('title', 'status', 'assigned_to', 'queue', 'hidden_submitter_email',)

**Comment by jefmoura** [comment]
We have to insert a related field on order model to correctly list the tacked orders.
In this [Stackoverflow link](http://stackoverflow.com/questions/28303992/how-to-hide-field-depend-on-condition-odoo) we can see how to create.
